### ISSUE TITLE
SEGV found in cs104_server.c

### ISSUE THREAD

**Issue by Rrooach** [mz-automation/lib60870#53]
Hello, I found a __SEGV__  inlib60870/lib60870-C/examples/cs104_server/simple_server.c, gdb debug trace to  

>0x000000000059ae6e in CP56Time2a_getHour (self=<optimized out>) at >src/iec60870/apl/cpXXtime2a.c:583
>583         return (self->encodedValue[3] & 0x1f);

where the return seems to cause an unexpected SEGV error.

__Below are steps followed to reproduce crash__
Download latest source code from: /mz-automation/lib60870/, compiled with clang and ASAN```export CFLAGS="-g -fsanitize=address" LDFLAGS="-fsanitize=address"```before make

__Input data__
[crash.zip](https://github.com/mz-automation/lib60870/files/3737209/crash.zip)

__ASAN Output__ 
```
ASAN:DEADLYSIGNAL
=================================================================
==7137==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000013 (pc 0x00000059ae6e bp 0x7f81dbafbd70 sp 0x7f81dbafbad0 T4)                                                                                 ==7137==The signal is caused by a READ memory access.                                                                                                                                                              ==7137==Hint: address points to the zero page.
    #0 0x59ae6d in CP56Time2a_getHour /root/temp/iec/lib60870/lib60870-C/src/iec60870/apl/cpXXtime2a.c:583:13
    #1 0x511109 in printCP56Time2a /root/temp/iec/lib60870/lib60870-C/examples/cs104_server/simple_server.c:23:45
    #2 0x511109 in clockSyncHandler /root/temp/iec/lib60870/lib60870-C/examples/cs104_server/simple_server.c:51
    #3 0x58ced4 in handleASDU /root/temp/iec/lib60870/lib60870-C/src/iec60870/cs104/cs104_slave.c:1790:21
    #4 0x58ced4 in handleMessage /root/temp/iec/lib60870/lib60870-C/src/iec60870/cs104/cs104_slave.c:2043
    #5 0x5882b6 in connectionHandlingThread /root/temp/iec/lib60870/lib60870-C/src/iec60870/cs104/cs104_slave.c:2410:21
    #6 0x5a0962 in destroyAutomaticThread /root/temp/iec/lib60870/lib60870-C/src/hal/thread/linux/thread_linux.c:87:2
    #7 0x7f81e0a846b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #8 0x7f81dfe8f41c in clone /build/glibc-LK5gWL/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/temp/iec/lib60870/lib60870-C/src/iec60870/apl/cpXXtime2a.c:583:13 in CP56Time2a_getHour
Thread T4 created by T1 here:
    #0 0x431d2d in __interceptor_pthread_create (/root/temp/iec/lib60870/lib60870-C/examples/cs104_server/simple_server+0x431d2d)
    #1 0x5a05eb in Thread_start /root/temp/iec/lib60870/lib60870-C/src/hal/thread/linux/thread_linux.c:98:3
    #2 0x7f81e0a846b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Thread T1 created by T0 here:
    #0 0x431d2d in __interceptor_pthread_create (/root/temp/iec/lib60870/lib60870-C/examples/cs104_server/simple_server+0x431d2d)
    #1 0x5a06bb in Thread_start /root/temp/iec/lib60870/lib60870-C/src/hal/thread/linux/thread_linux.c:102:3

==7137==ABORTING
```

**Comment by mzillgith** [comment]
Thanks for the info. I added some code to protect against corrupted messages. Should be fixed now. If now please reopen.
